### PR TITLE
c++17 enabled in cmake

### PR DESCRIPTION
**Pull request by dcoeurjo**

### CODE REVIEW

**Comment by dcoeurjo** [comment]
Would you have an command-line example?

**Comment by BDoignies** [comment]
CMake build has two build options : -DCPLEX=ON, -DGLPK=ON. Both can be compiled simultaneously as they produce different executable (namely: matbuilder_cplex, matbuilder_glpk). 

Commandlines arguments are the same as the original repository; though `--check` and `--header` are not yet supported. 

The new tool "expand" (which produce a LP or MPS file) has the following arguments : 

* -i: profile
* -m: already generated matrices
* -o: output file
* --seed: seed
* --no-seed: remove random objective
* --format [LP or MPS] : format of output

I'll add more documentation later.

**Comment by BDoignies** [comment]
I updated the readme to include more informations. Anything to add before I merge the PR ?

**Comment by dcoeurjo** [comment]
Please merge. I'll do another PR if needed

**Pull request merged**
